/**
 * Canonical visual inventory for the Palavras do Universo experience.
 *
 * Keeping these paths in one place prevents the homepage from drifting back
 * into a mix of legacy `/icons` and generic `/assets` references.
 */
export const PDU_ASSETS = {
  brand: {
    symbol: "/assets/palavras-symbol.webp",
    mark: "/assets/palavrasuniverso-1600.webp",
    markDesktop: "/assets/palavrasuniverso-1600.webp",
    markMobile: "/assets/palavrasuniverso-mobile.webp",
    fullWordmark: "/assets/palavrasuniverso.webp",
    newWordmark: "/assets/pdu-new-wordmark-transparent-ofi.webp",
    heroMarkRotation: [
      { assetPath: "/assets/new-pdu-dock5.webp" },
      { assetPath: "/assets/new-pdu-dock4.webp" },
      { assetPath: "/assets/new-pdu-dock3.webp" },
      { assetPath: "/assets/pdu-logomark1.webp" },
      {
        assetPath: "/assets/pdu-dock.webp",
        mobileAssetPath: "/assets/pdu-dock-mobile.webp",
      },
      {
        assetPath: "/assets/palavrasuniverso-1600.webp",
        mobileAssetPath: "/assets/palavrasuniverso-mobile.webp",
      },
    ],
  },
  icons: {
    book: "/assets/pdu-icon-book.webp",
    bookmark: "/assets/pdu-icon-bookmark.webp",
    heart: "/assets/pdu-icon-heart.webp",
    meditation: "/assets/pdu-icon-meditation.webp",
    moon: "/assets/pdu-icon-moon.webp",
    shield: "/assets/pdu-icon-shield.webp",
    sprout: "/assets/pdu-icon-sprout.webp",
  },
  editorial: {
    crystal: "/assets/CRYSTAL.webp",
    key: "/assets/key.webp",
    mirror: "/assets/mirror.webp",
    portal: "/assets/portal.webp",
  },
  ambient: {
    allConnected: "/assets/allconnected.webp",
    candle: "/assets/candle.webp",
    mandala: "/assets/mandalaspecial.webp",
  },
  symbolic: {
    hourglass: "/assets/AMPULHETA.webp",
    bell: "/assets/bell.webp",
    bigEye: "/assets/bigeye.webp",
    bigGem: "/assets/biggem.webp",
    butterfly: "/assets/butterfly.webp",
    chalice: "/assets/calice.webp",
    threeCardsEditorial: "/assets/caminho3cartas.webp",
    // The old `cards.webp` reference no longer exists in the asset folder.
    // Keep this semantic slot pointed at the maintained three-card artwork.
    cards: "/assets/product-caminho-das-3-cartas.webp",
    scepter: "/assets/cetro.webp",
    direction: "/assets/direction.webp",
    dreamFilter: "/assets/filtrodossonhos.webp",
    fire: "/assets/firebase.webp",
    vessel: "/assets/garrafa.webp",
    geisha: "/assets/gueixa.webp",
    hand: "/assets/hand.webp",
    dragonfly: "/assets/libelula.webp",
    lotus: "/assets/lotus.webp",
    magicBook: "/assets/magicbook.webp",
    mandalaBase: "/assets/mandala.webp",
    mandalaDeep: "/assets/mandala2.webp",
    meditation: "/assets/meditation.webp",
    oracle: "/assets/oraculo.webp",
    consultation: "/assets/pdu-consulta.webp",
    dock: "/assets/pdu-dock.webp",
    essence: "/assets/pdu-essence.webp",
    feather: "/assets/pena.webp",
    pendulum: "/assets/pendulo.webp",
    wingOracle: "/assets/wing-oracle.webp",
    zodiac: "/assets/zodiac.webp",
  },
  products: {
    messageOfTheDay: "/assets/product-mensagem-do-dia.webp",
    cardOfTheDay: "/assets/product-carta-do-dia.webp",
    cardOfTheDayMobile: "/assets/product-carta-do-dia-mobile.webp",
    cardOfTheDayDisplay: "/assets/product-carta-do-dia.webp",
    urgentClarity: "/assets/product-clareza-urgente.webp",
    threeCardPath: "/assets/caminho3cartas.webp",
    threeCardPathMobile: "/assets/product-caminho-das-3-cartas-mobile.webp",
    threeCardPathDisplay: "/assets/product-caminho-das-3-cartas.webp",
    loveSignals: "/assets/pdu-heart.webp",
    loveSignalsMobile: "/assets/pdu-heart-mobile.webp",
    loveSignalsDisplay: "/assets/pdu-heart-mobile.webp",
    weekEnergy: "/assets/pdu-ciclos.webp",
    weekEnergyMobile: "/assets/pdu-ciclos-mobile.webp",
    weekEnergyDisplay: "/assets/pdu-ciclos-mobile.webp",
    momentMap: "/assets/pdu-target.webp",
    momentMapMobile: "/assets/pdu-target-mobile.webp",
    momentMapDisplay: "/assets/pdu-target-mobile.webp",
  },
  surfaces: {
    account: "/assets/palavras-symbol.webp",
    legalPrivacy: "/assets/pdu-icon-shield.webp",
    legalTerms: "/assets/pdu-icon-book.webp",
    legalRefunds: "/assets/pdu-icon-bookmark.webp",
    voucherInvite: "/assets/pdu-icon-sprout.webp",
    voucherDiscount: "/assets/pdu-icon-shield.webp",
    voucherAccess: "/assets/pdu-icon-moon.webp",
    action: "/assets/pdu-icon-sprout.webp",
    actionComplete: "/assets/pdu-icon-shield.webp",
    access: "/assets/pdu-icon-shield.webp",
    readings: "/assets/pdu-icon-book.webp",
    saved: "/assets/pdu-icon-bookmark.webp",
    movement: "/assets/pdu-icon-sprout.webp",
    profile: "/assets/pdu-icon-meditation.webp",
    map: "/assets/pdu-icon-moon.webp",
  },
} as const;
