/**
 * Canonical visual inventory for the Palavras do Universo experience.
 *
 * Keeping these paths in one place prevents the homepage from drifting back
 * into a mix of legacy `/icons` and generic `/assets` references.
 */
export const PDU_ASSETS = {
  brand: {
    symbol: "/assets/palavras-symbol.webp",
    mark: "/assets/palavrasuniverso-1600.webp",
    markDesktop: "/assets/palavrasuniverso-1600.webp",
    markMobile: "/assets/palavrasuniverso-mobile.webp",
    fullWordmark: "/assets/palavrasuniverso.webp",
    newWordmark: "/assets/pdu-new-wordmark-transparent-ofi.webp",
    heroMarkRotation: [
      {
        assetPath: "/assets/new-pdu-dock.webp",
        mobileAssetPath: "/assets/pdu-hero-new-dock-mobile.webp",
      },
      {
        assetPath: "/assets/new-pdu-dock3.webp",
        mobileAssetPath: "/assets/pdu-hero-new-dock3-mobile.webp",
      },
      {
        assetPath: "/assets/new-pdu-dock4.webp",
        mobileAssetPath: "/assets/pdu-hero-new-dock4-mobile.webp",
      },
      {
        assetPath: "/assets/new-pdu-dock5.webp",
        mobileAssetPath: "/assets/pdu-hero-new-dock5-mobile.webp",
      },
      {
        assetPath: "/assets/pdu-dock.webp",
        mobileAssetPath: "/assets/pdu-dock-mobile.webp",
      },
      {
        assetPath: "/assets/palavrasuniverso-1600.webp",
        mobileAssetPath: "/assets/palavrasuniverso-mobile.webp",
      },
    ],
  },
  icons: {
    book: "/assets/pdu-icon-book.webp",
    bookmark: "/assets/pdu-icon-bookmark.webp",
    heart: "/assets/pdu-icon-heart.webp",
    meditation: "/assets/pdu-icon-meditation.webp",
    moon: "/assets/pdu-icon-moon.webp",
    shield: "/assets/pdu-icon-shield.webp",
    sprout: "/assets/pdu-icon-sprout.webp",
  },
  editorial: {
    crystal: "/assets/CRYSTAL.webp",
    key: "/assets/key.webp",
    mirror: "/assets/mirror.webp",
    portal: "/assets/portal.webp",
  },
  ambient: {
    allConnected: "/assets/allconnected.webp",
    candle: "/assets/candle.webp",
    mandala: "/assets/mandalaspecial.webp",
  },
  homepage: {
    dailyReadingBookCards: "/assets/homepage/pdu-home-daily-reading-book-cards.webp",
    savedMessagesBookmark: "/assets/homepage/pdu-home-saved-messages-bookmark.webp",
    questionCard: "/assets/homepage/pdu-home-question-card.webp",
    portalAccessKey: "/assets/homepage/pdu-home-portal-access-key.webp",
    completedActionsChecklist: "/assets/homepage/pdu-home-completed-actions-checklist.webp",
    growthPath: "/assets/homepage/pdu-home-growth-path.webp",
    readingBook: "/assets/homepage/pdu-home-reading-book.webp",
    securePaymentValue: "/assets/homepage/pdu-home-secure-payment-value.webp",
  },
  symbolic: {
    hourglass: "/assets/AMPULHETA.webp",
    bell: "/assets/bell.webp",
    bigEye: "/assets/bigeye.webp",
    bigEyeMobile: "/assets/bigeye-mobile.webp",
    bigGem: "/assets/biggem.webp",
    butterfly: "/assets/butterfly.webp",
    chalice: "/assets/calice.webp",
    threeCardsEditorial: "/assets/caminho3cartas.webp",
    // The old `cards.webp` reference no longer exists in the asset folder.
    // Keep this semantic slot pointed at the maintained three-card artwork.
    cards: "/assets/product-caminho-das-3-cartas.webp",
    scepter: "/assets/cetro.webp",
    direction: "/assets/direction.webp",
    dreamFilter: "/assets/filtrodossonhos.webp",
    fire: "/assets/firebase.webp",
    vessel: "/assets/garrafa.webp",
    geisha: "/assets/gueixa.webp",
    hand: "/assets/hand.webp",
    handMobile: "/assets/hand-mobile.webp",
    dragonfly: "/assets/libelula.webp",
    lotus: "/assets/lotus.webp",
    magicBook: "/assets/magicbook.webp",
    mandalaBase: "/assets/mandala.webp",
    mandalaDeep: "/assets/mandala2.webp",
    meditation: "/assets/meditation.webp",
    oracle: "/assets/oraculo.webp",
    consultation: "/assets/pdu-consulta.webp",
    dock: "/assets/pdu-dock.webp",
    essence: "/assets/pdu-essence.webp",
    feather: "/assets/pena.webp",
    pendulum: "/assets/pendulo.webp",
    wingOracle: "/assets/wing-oracle.webp",
    wingOracleMobile: "/assets/wing-oracle-mobile.webp",
    zodiac: "/assets/zodiac.webp",
  },
  products: {
    messageOfTheDay: "/assets/product-mensagem-do-dia.webp",
    startFreeSpread: "/assets/product-start-free-spread.webp",
    startFreeSpreadIcon: "/assets/product-start-free-spread-icon.webp",
    cardOfTheDay: "/assets/product-carta-do-dia.webp",
    cardOfTheDayMobile: "/assets/product-carta-do-dia-mobile.webp",
    cardOfTheDayDisplay: "/assets/product-carta-do-dia.webp",
    urgentClarity: "/assets/product-clareza-urgente.webp",
    oneQuestionSpread: "/assets/product-one-question-spread.webp",
    oneQuestionSpreadIcon: "/assets/product-one-question-spread-icon.webp",
    threeCardPath: "/assets/caminho3cartas.webp",
    threeCardPathMobile: "/assets/product-caminho-das-3-cartas-mobile.webp",
    threeCardPathDisplay: "/assets/product-caminho-das-3-cartas.webp",
    loveSignals: "/assets/pdu-heart.webp",
    loveSignalsMobile: "/assets/pdu-heart-mobile.webp",
    loveSignalsDisplay: "/assets/pdu-heart-mobile.webp",
    weekEnergy: "/assets/pdu-ciclos.webp",
    weekEnergyMobile: "/assets/pdu-ciclos-mobile.webp",
    weekEnergyDisplay: "/assets/pdu-ciclos-mobile.webp",
    momentMap: "/assets/pdu-target.webp",
    momentMapMobile: "/assets/pdu-target-mobile.webp",
    momentMapDisplay: "/assets/pdu-target-mobile.webp",
    journeyCircleSpread: "/assets/product-journey-circle-spread.webp",
    journeyCircleSpreadIcon: "/assets/product-journey-circle-spread-icon.webp",
  },
  productIcons: {
    cardOfTheDay: "/assets/product-icons/carta-do-dia-premium.webp",
    urgentClarity: "/assets/product-icons/clareza-urgente-premium.webp",
    threeCardPath: "/assets/product-icons/caminho-das-3-cartas-premium.webp",
    loveSignals: "/assets/product-icons/sinais-do-amor-premium.webp",
    diamond: "/assets/product-icons/tirada-diamante-icon.webp",
    flyingBird: "/assets/product-icons/tirada-passaro-icon.webp",
    key: "/assets/product-icons/tirada-chave-icon.webp",
    mirror: "/assets/product-icons/tirada-espelho-icon.webp",
    celticCross: "/assets/product-icons/tirada-cruz-icon.webp",
    relationship: "/assets/product-icons/tirada-relacionar-icon.webp",
    paradox: "/assets/product-icons/tirada-paradoxo-icon.webp",
    weekEnergy: "/assets/product-icons/energia-da-semana-premium.webp",
    momentMap: "/assets/product-icons/mapa-do-momento-premium.webp",
  },
  spreads: {
    cardOfTheDay: "/assets/spreads/carta-do-dia.webp",
    cardOfTheDayMobile: "/assets/spreads/mobile/carta-do-dia-mobile.webp",
    threeCardPath: "/assets/spreads/caminho-das-3-cartas.webp",
    threeCardPathMobile: "/assets/spreads/mobile/caminho-das-3-cartas-mobile.webp",
    loveSignals: "/assets/spreads/sinais-do-amor.webp",
    loveSignalsMobile: "/assets/spreads/mobile/sinais-do-amor-mobile.webp",
    urgentClarity: "/assets/spreads/clareza-urgente.webp",
    urgentClarityMobile: "/assets/spreads/mobile/clareza-urgente-mobile.webp",
    diamond: "/assets/spreads/o-diamante.webp",
    diamondMobile: "/assets/spreads/mobile/o-diamante-mobile.webp",
    flyingBird: "/assets/spreads/o-passaro-voando.webp",
    flyingBirdMobile: "/assets/spreads/mobile/o-passaro-voando-mobile.webp",
    key: "/assets/spreads/a-chave.webp",
    keyMobile: "/assets/spreads/mobile/a-chave-mobile.webp",
    mirror: "/assets/spreads/o-espelho.webp",
    mirrorMobile: "/assets/spreads/mobile/o-espelho-mobile.webp",
    celticCross: "/assets/spreads/cruz-celta.webp",
    celticCrossMobile: "/assets/spreads/mobile/cruz-celta-mobile.webp",
    relationship: "/assets/spreads/relacionamento.webp",
    relationshipMobile: "/assets/spreads/mobile/relacionamento-mobile.webp",
    paradox: "/assets/spreads/o-paradoxo.webp",
    paradoxMobile: "/assets/spreads/mobile/o-paradoxo-mobile.webp",
    weekEnergy: "/assets/spreads/energia-da-semana.webp",
    weekEnergyMobile: "/assets/spreads/mobile/energia-da-semana-mobile.webp",
    momentMap: "/assets/spreads/mapa-do-momento.webp",
    momentMapMobile: "/assets/spreads/mobile/mapa-do-momento-mobile.webp",
  },
  spreadLayouts: {
    diamond: "/assets/spreads/layouts/tirada-diamante-pdu.webp",
    diamondMobile: "/assets/spreads/layouts/mobile/tirada-diamante-pdu-mobile.webp",
    flyingBird: "/assets/spreads/layouts/tirada-passaro-pdu.webp",
    flyingBirdMobile: "/assets/spreads/layouts/mobile/tirada-passaro-pdu-mobile.webp",
    key: "/assets/spreads/layouts/tirada-chave-pdu.webp",
    keyMobile: "/assets/spreads/layouts/mobile/tirada-chave-pdu-mobile.webp",
    mirror: "/assets/spreads/layouts/tirada-espelho-pdu.webp",
    mirrorMobile: "/assets/spreads/layouts/mobile/tirada-espelho-pdu-mobile.webp",
    celticCross: "/assets/spreads/layouts/tirada-cruz-pdu.webp",
    celticCrossMobile: "/assets/spreads/layouts/mobile/tirada-cruz-pdu-mobile.webp",
    relationship: "/assets/spreads/layouts/tirada-relacionar-pdu.webp",
    relationshipMobile: "/assets/spreads/layouts/mobile/tirada-relacionar-pdu-mobile.webp",
    paradox: "/assets/spreads/layouts/tirada-paradoxo-pdu.webp",
    paradoxMobile: "/assets/spreads/layouts/mobile/tirada-paradoxo-pdu-mobile.webp",
  },
  surfaces: {
    account: "/assets/palavras-symbol.webp",
    legalPrivacy: "/assets/pdu-icon-shield.webp",
    legalTerms: "/assets/pdu-icon-book.webp",
    legalRefunds: "/assets/pdu-icon-bookmark.webp",
    voucherInvite: "/assets/pdu-icon-sprout.webp",
    voucherDiscount: "/assets/pdu-icon-shield.webp",
    voucherAccess: "/assets/pdu-icon-moon.webp",
    action: "/assets/pdu-icon-sprout.webp",
    actionComplete: "/assets/homepage/pdu-home-completed-actions-checklist.webp",
    access: "/assets/homepage/pdu-home-portal-access-key.webp",
    readings: "/assets/homepage/pdu-home-reading-book.webp",
    saved: "/assets/homepage/pdu-home-saved-messages-bookmark.webp",
    movement: "/assets/homepage/pdu-home-growth-path.webp",
    profile: "/assets/pdu-icon-meditation.webp",
    map: "/assets/pdu-icon-moon.webp",
  },
} as const;
