"use client";

import { CalendarDays, CheckCircle2, Clock3, LockKeyhole, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { EDU_READING_AVAILABILITY, EDU_READING_OFFERS } from "@/lib/edu-reading-offers";
import { formatPriceCents, type ProductCurrency } from "@/lib/product/pricing";
import { useI18n } from "@/components/I18nProvider";

export function EduReadingBookingPanel() {
  const { locale } = useI18n();
  const isEnglish = locale === "en";
  const [currency, setCurrency] = useState<ProductCurrency>(isEnglish ? "GBP" : "BRL");
  const [step, setStep] = useState(1);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [intention, setIntention] = useState("");
  const [offerId, setOfferId] = useState<string | null>(null);
  const selectedOffer = useMemo(() => EDU_READING_OFFERS.find((offer) => offer.id === offerId) ?? null, [offerId]);
  const hasAvailability = EDU_READING_AVAILABILITY.length > 0;

  function continueToSchedule(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (name.trim() && email.trim()) setStep(2);
  }

  return <section id="agendar" className="scroll-mt-24 bg-[#ede1cf] px-4 py-20 sm:px-6 lg:px-8 lg:py-28">
    <div className="mx-auto max-w-6xl">
      <div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#8e674d]">{isEnglish ? "Request your reading" : "Solicite sua leitura"}</p><h2 className="brand-serif mt-4 text-4xl font-semibold sm:text-5xl">{isEnglish ? "Choose your moment with care." : "Escolha seu momento com cuidado."}</h2><p className="mt-5 leading-8 text-[#6f5d55]">{isEnglish ? "First, share only what is needed. Then choose an available time and the reading that best fits your question." : "Primeiro, compartilhe apenas o necessário. Depois, escolha um horário disponível e a leitura que mais combina com sua pergunta."}</p></div>
      <div className="mt-10 grid gap-5 lg:grid-cols-[0.78fr_1.22fr]">
        <aside className="rounded-[1.5rem] bg-[#241b18] p-6 text-[#fff7e8]"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#f4d58d]">{isEnglish ? "Your path" : "Seu caminho"}</p><ol className="mt-6 space-y-5 text-sm">{[[1, isEnglish ? "Your details" : "Suas informações"], [2, isEnglish ? "Date and time" : "Data e horário"], [3, isEnglish ? "Your reading" : "Sua tirada"]].map(([number, label]) => <li key={String(number)} className={`flex items-center gap-3 ${step === number ? "text-[#f4d58d]" : "text-[#d8ccc0]"}`}><span className={`grid h-7 w-7 place-items-center rounded-full border ${step === number ? "border-[#f4d58d] bg-[#f4d58d] text-[#241b18]" : "border-white/30"}`}>{number}</span>{label}</li>)}</ol><div className="mt-10 border-t border-white/15 pt-5 text-xs leading-6 text-[#d8ccc0]"><LockKeyhole className="mb-2" size={16}/>{isEnglish ? "No payment is collected until the date, format and conditions are confirmed." : "Nenhum pagamento é cobrado antes de confirmar data, formato e condições."}</div></aside>
        <div className="rounded-[1.5rem] border border-[#d8c3a6] bg-[#fffaf2] p-6 sm:p-8">
          {step === 1 ? <form onSubmit={continueToSchedule}><div className="flex items-center gap-3"><Sparkles className="text-[#9d753e]" size={20}/><h3 className="brand-serif text-3xl font-semibold">{isEnglish ? "A little about you" : "Um pouco sobre você"}</h3></div><p className="mt-3 text-sm leading-7 text-[#6f5d55]">{isEnglish ? "You do not need to tell your full story here." : "Você não precisa contar toda a sua história aqui."}</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">{isEnglish ? "First name" : "Seu nome"}<input required value={name} onChange={(event) => setName(event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-[#d8c3a6] bg-white px-4 font-normal outline-none focus:border-[#8e674d]" /></label><label className="text-sm font-semibold">{isEnglish ? "Email" : "E-mail"}<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-[#d8c3a6] bg-white px-4 font-normal outline-none focus:border-[#8e674d]" /></label></div><label className="mt-4 block text-sm font-semibold">{isEnglish ? "What would you like to look at? (optional)" : "O que você gostaria de olhar? (opcional)"}<textarea value={intention} onChange={(event) => setIntention(event.target.value)} rows={4} className="mt-2 w-full rounded-xl border border-[#d8c3a6] bg-white p-4 font-normal outline-none focus:border-[#8e674d]" /></label><button className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#241b18] px-5 py-3 text-sm font-semibold text-white">{isEnglish ? "See availability" : "Ver disponibilidade"}<CalendarDays size={17}/></button></form> : null}
          {step === 2 ? <div><div className="flex items-center gap-3"><CalendarDays className="text-[#9d753e]" size={20}/><h3 className="brand-serif text-3xl font-semibold">{isEnglish ? "Date and time" : "Data e horário"}</h3></div>{hasAvailability ? <p className="mt-4 text-[#6f5d55]">{isEnglish ? "Choose a time that works for you." : "Escolha um horário que funcione para você."}</p> : <div className="mt-6 rounded-2xl border border-[#d8c3a6] bg-[#f7f0e5] p-5"><p className="font-semibold text-[#2c1f1b]">{isEnglish ? "The schedule will open soon." : "A agenda será aberta em breve."}</p><p className="mt-2 text-sm leading-7 text-[#6f5d55]">{isEnglish ? "No times are shown until Edu defines real availability. Your details stay only in this browser for now." : "Nenhum horário é exibido até que o Edu defina disponibilidade real. Seus dados ficam apenas neste navegador por enquanto."}</p></div>}<button type="button" onClick={() => setStep(3)} className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-full border border-[#8e674d]/45 px-5 py-3 text-sm font-semibold text-[#6f5134]">{isEnglish ? "Explore readings first" : "Conhecer as tiradas primeiro"}</button></div> : null}
          {step === 3 ? <div><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-3"><Clock3 className="text-[#9d753e]" size={20}/><h3 className="brand-serif text-3xl font-semibold">{isEnglish ? "Choose your reading" : "Escolha sua tirada"}</h3></div><p className="mt-3 text-sm leading-7 text-[#6f5d55]">{isEnglish ? "Prices include the time reserved for your session." : "Os valores incluem o tempo reservado para o seu atendimento."}</p></div><div className="rounded-full border border-[#d8c3a6] p-1">{(["BRL", "GBP"] as ProductCurrency[]).map((item) => <button type="button" onClick={() => setCurrency(item)} key={item} className={`rounded-full px-3 py-2 text-xs font-bold ${currency === item ? "bg-[#241b18] text-white" : "text-[#6f5d55]"}`}>{item}</button>)}</div></div><div className="mt-7 grid gap-3">{EDU_READING_OFFERS.map((offer) => <button type="button" onClick={() => setOfferId(offer.id)} key={offer.id} className={`w-full rounded-2xl border p-5 text-left transition ${offer.id === offerId ? "border-[#8e674d] bg-[#f7eddb]" : "border-[#d8c3a6] bg-white hover:border-[#8e674d]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-[#2c1f1b]">{offer.title}</p><p className="mt-1 text-sm text-[#6f5d55]">{offer.cards} {isEnglish ? "cards" : "cartas"} · {offer.durationLabel}</p></div><strong className="text-[#6f5134]">{formatPriceCents(offer.priceCents[currency], currency)}</strong></div><p className="mt-3 text-sm leading-6 text-[#6f5d55]">{isEnglish ? offer.description.en : offer.description.pt}</p></button>)}</div>{selectedOffer ? <div className="mt-6 flex items-center gap-3 rounded-xl bg-[#dceee5] p-4 text-sm text-[#315d51]"><CheckCircle2 size={19}/>{isEnglish ? `${selectedOffer.title} selected. The next step will open when availability is defined.` : `${selectedOffer.title} selecionado. A próxima etapa será aberta quando a disponibilidade for definida.`}</div> : null}</div> : null}
        </div>
      </div>
    </div>
  </section>;
}
