insert into public.oracle_products (
  product_key,
  title,
  product_type,
  status,
  price_cents,
  currency,
  access_model,
  provider_price_id,
  provider_product_id,
  short_description,
  promise,
  best_for,
  not_for,
  value_position,
  funnel_stage,
  cta_label,
  route_path,
  sort_order,
  included_in,
  metadata
)
values (
  'teste_checkout_50',
  'Teste de Checkout',
  'one_time',
  'active',
  50,
  'BRL',
  'one_time',
  null,
  null,
  'Produto interno para validar pagamento, webhook e entrega.',
  'Confirmar o fluxo completo de compra com valor mínimo.',
  'Teste operacional antes de divulgação ou campanha.',
  'Uso público ou oferta comercial.',
  'Produto oculto de validação interna.',
  'conversion',
  'Testar checkout',
  null,
  999,
  array[]::text[],
  '{"internal_test":true,"hidden":true,"purpose":"checkout_validation","depth":"test"}'::jsonb
)
on conflict (product_key) do update set
  title = excluded.title,
  product_type = excluded.product_type,
  status = excluded.status,
  price_cents = excluded.price_cents,
  currency = excluded.currency,
  access_model = excluded.access_model,
  provider_price_id = excluded.provider_price_id,
  provider_product_id = excluded.provider_product_id,
  short_description = excluded.short_description,
  promise = excluded.promise,
  best_for = excluded.best_for,
  not_for = excluded.not_for,
  value_position = excluded.value_position,
  funnel_stage = excluded.funnel_stage,
  cta_label = excluded.cta_label,
  route_path = excluded.route_path,
  sort_order = excluded.sort_order,
  included_in = excluded.included_in,
  metadata = public.oracle_products.metadata || excluded.metadata,
  updated_at = now();
